# NOTE: update this with your service name
service: notes-api

# Create an optimized package for our functions
package:
    individually: true

plugins:
    - serverless-bundle # Package our functions with Webpack
    - serverless-offline
    - serverless-dotenv-plugin # Load .env as environment variables

custom:
    # Our stage is based on what is passed in when running serverless
    # commands. Or falls back to what we have set in the provider section.
    stage: ${opt:stage, self:provider.stage}
    # Name of the SST app that's deploying our infrastructure
    sstApp: ${self:custom.stage}-notes-infra

provider:
    name: aws
    runtime: nodejs10.x
    stage: dev
    region: eu-central-1

    # These environment variables are made available to our functions
    # under process.env.
    environment:
        stripeSecretKey: ${env:STRIPE_SECRET_KEY}
        tableName: !ImportValue "${self:custom.sstApp}-TableName"

    # 'iamRoleStatements' defines the permission policy for the Lambda function.
    # In this case Lambda functions are granted with permissions to access DynamoDB.
    iamRoleStatements:
        - Effect: Allow
          Action:
              - dynamodb:Scan
              - dynamodb:Query
              - dynamodb:GetItem
              - dynamodb:PutItem
              - dynamodb:UpdateItem
              - dynamodb:DeleteItem
              - dynamodb:DescribeTable
          # Restrict our IAM role permissions to
          # the specific table for the stage
          Resource:
              - !ImportValue "${self:custom.sstApp}-TableArn"

functions:
    # Defines an HTTP API endpoint that calls the main function in create.js
    # - path: url path is /notes
    # - method: POST request
    # - cors: enabled CORS (Cross-Origin Resource Sharing) for browser cross
    #     domain api call
    # - authorizer: authenticate using the AWS IAM role
    create:
        handler: create.main
        events:
            - http:
                  path: notes
                  method: post
                  cors: true
                  authorizer: aws_iam
    get:
        handler: get.main
        events:
            - http:
                  path: notes/{id}
                  method: get
                  cors: true
                  authorizer: aws_iam
    list:
        handler: list.main
        events:
            - http:
                  path: notes
                  method: get
                  cors: true
                  authorizer: aws_iam
    update:
        handler: update.main
        events:
            - http:
                  path: notes/{id}
                  method: put
                  cors: true
                  authorizer: aws_iam
    delete:
        handler: delete.main
        events:
            - http:
                  path: notes/{id}
                  method: delete
                  cors: true
                  authorizer: aws_iam
    billing:
        handler: billing.main
        events:
            - http:
                  path: billing
                  method: post
                  cors: true
                  authorizer: aws_iam

# Create our resources with separate CloudFormation templates
resources:
    # API Gateway Errors
    - ${file(resources/api-gateway-errors.yml)}
    # Cognito Identity Pool Policy
    - ${file(resources/cognito-policy.yml)}
